obj-m += dev1.o
all:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules
clean:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean



app:test.o
	gcc -o app test.o
app.o:test.c
	gcc -c test.c -I /home/viktoria/develop/day4
